### ISSUE TITLE
Getting Installer to Boot

### ISSUE THREAD

**Issue by MatthewHallCom** [laelsirus/Dell-Latitude-5290-2-in-1-UHD620-iGPU-CLOVER#1]
Hey @laelsirus ! Thanks for the hard work on this! 

How have you managed to get the installer to boot? I've tried the Vanilla Hackintosh Guide as well as using your kexts and still getting a variety of different panics when trying to boot an installer.

**Comment by laelsirus** [comment]
> Hey @laelsirus ! Thanks for the hard work on this!
> 
> How have you managed to get the installer to boot? I've tried the Vanilla Hackintosh Guide as well as using your kexts and still getting a variety of different panics when trying to boot an installer.

Thank you!
Nothing special.

Make boot USB with terminal command line and install clover bootloader then copy prepared efi files.
Since the DSDT differs depending on the detailed hardware specification and BIOS version of the device, it is recommended to install macOS without the DSDT.aml, and then renew the DSDT patch manually.

What's the spec of yours?

**Comment by MatthewHallCom** [comment]
Hmmm yeah mine is still not making it to boot

i7-8650U
16GB RAM
256GB SSD
UHD 620
Latest BIOS Driver

It has the Thunderbolt 3 port instead of normal USB-C

**Comment by laelsirus** [comment]
> Hmmm yeah mine is still not making it to boot
> 
> i7-8650U
> 16GB RAM
> 256GB SSD
> UHD 620
> Latest BIOS Driver
> 
> It has the Thunderbolt 3 port instead of normal USB-C

Thunderbolt seems to be a problem.
Try booting except DSDT.aml, SSDT-UIAC.aml, SSDT-USBX.aml and USBPorts.kext
What panic showing?

Plus add USBInjectAll.kext

**Comment by MatthewHallCom** [comment]
Getting rid of those did it! Will continue install and update you

**Comment by laelsirus** [comment]
> Getting rid of those did it! Will continue install and update you

Good! I'll check.
