### ISSUE TITLE
Kernel Panic every time without ACPI patched, Only VirtualSMC kext

### ISSUE THREAD

**Issue by luongdev** [laelsirus/Dell-Latitude-5290-2-in-1-UHD620-iGPU-CLOVER#2]
Hi Bro, 

Sorry about my poor English.
I Used Clover floder to create Mojave installer but kernel panic everytime.
My 5290 100 percent same with your device.

Can you help me, please!

**Comment by laelsirus** [comment]
Sorry for late.
There were some problems with the VoodooPS2Controller.kext
Fixed this issue a few days ago, so try again with the most recent release and please let me know the results
